Add GitHub Actions workflow for hello and goodbye

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,1 +1,19 @@
-
+name: "01 - Building Blocks"
+on: push
+jobs:
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Hello
+        run: echo "Hello, world!"
+echo-Failed:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail Step
+        run: echo "This step is designed to fail" 
+         exit 1        
+echo-Goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Goodbye
+        run: echo "Goodbye, world!"      
